name: Pull Requested

on:
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
      with:
        image: tonistiigi/binfmt:latest
        platforms: all
    - name: pull image
      env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.TEST_SECRET_PULL }}
      run:  |
            echo ${steps.qemu.outputs.platforms}
            docker version
            echo ${LARGE_SECRET_PASSPHRASE} >test.pop
            cat test.pop
            docker login -u _json_key --password-stdin https://us.gcr.io < test.pop
            docker pull us.gcr.io/powergatedev/powerfly
            docker logout https://us.gcr.io
