name: Pull Requested

on:
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
      with:
        image: tonistiigi/binfmt:latest
        platforms: all
    - name: pull image
      run:  |
            echo ${{ steps.qemu.outputs.platforms }}
            docker pull us.gcr.io/powergatedev/powerfly
